<?php
/**
 * Fonte única de dados dos projetos.
 * Para adicionar um novo projeto, basta incluir um novo item neste array.
 * Tanto a index.php quanto portfolio/index.php consomem este arquivo.
 */
$projects = [
    [
        'slug'        => 'hcufg',
        'title'       => 'HC-UFG Hospital das Clínicas',
        'client'      => 'Universidade Federal de Goiás',
        'category'    => 'hospitalar',
        'label'       => 'Hospitalar',
        'image'       => 18,
        'area'        => '44.000 m²',
        'capacity'    => '1.500 TR',
        'description' => 'Hospital referência em GO com 20 pavimentos, filtragem HEPA, centro cirúrgico, UTIs e transplantados (H13).',
    ],
    [
        'slug'        => 'bancodobrasil',
        'title'       => 'Banco do Brasil — Sedes SBS',
        'client'      => 'Banco do Brasil S.A.',
        'category'    => 'corporativo',
        'label'       => 'Corporativo',
        'image'       => 19,
        'area'        => '96.135 m²',
        'capacity'    => '4.350 TR',
        'description' => '3 sedes no Setor Bancário Sul de Brasília com chillers parafuso e centrífugo, fancoils e pressurização.',
    ],
    [
        'slug'        => 'ccbb',
        'title'       => 'CCBB Brasília',
        'client'      => 'Banco do Brasil S.A.',
        'category'    => 'cultural',
        'label'       => 'Cultural',
        'image'       => 20,
        'area'        => '15.000 m²',
        'capacity'    => '900 TR',
        'description' => 'Centro Cultural Banco do Brasil com dual fluid de precisão para galerias, teatro (262 lugares) e cinema.',
    ],
    [
        'slug'        => 'geolab-siteii',
        'title'       => 'Geolab Site II',
        'client'      => 'Geolab Indústria Farmacêutica',
        'category'    => 'farmaceutico',
        'label'       => 'Farmacêutico',
        'image'       => 11,
        'area'        => '8.000 m²',
        'capacity'    => '900 TR',
        'description' => 'Salas limpas Grau B/C para produção de colírios, central de água gelada com VFD.',
    ],
    [
        'slug'        => 'injetaveis',
        'title'       => 'Prédio de Injetáveis',
        'client'      => 'Brainfarma',
        'category'    => 'farmaceutico',
        'label'       => 'Farmacêutico',
        'image'       => 1,
        'area'        => '1.800 m²',
        'capacity'    => '180 TR',
        'description' => 'Sistema de expansão indireta com FANCOIL e filtragem absoluta terminal.',
    ],
    [
        'slug'        => 'cosmed',
        'title'       => 'Prédio COSMED',
        'client'      => 'Brainfarma',
        'category'    => 'farmaceutico',
        'label'       => 'Farmacêutico',
        'image'       => 2,
        'area'        => '1.800 m²',
        'capacity'    => '160 TR',
        'description' => 'Área de produção de dermocosméticos com expansão direta e evaporadora TROX TKZ.',
    ],
    [
        'slug'        => 'geolab',
        'title'       => 'Geolab Farmacêutica',
        'client'      => 'Geolab',
        'category'    => 'farmaceutico',
        'label'       => 'Farmacêutico',
        'image'       => 8,
        'area'        => '25.000 m²',
        'capacity'    => '1.500 TR',
        'description' => 'Salas limpas para sólidos, efervescentes, semissólidos, líquidos e colírios com filtragem HEPA.',
    ],
    [
        'slug'        => 'brainfarma-fluxos',
        'title'       => 'Brainfarma Fluxos',
        'client'      => 'Brainfarma/Hypera',
        'category'    => 'farmaceutico',
        'label'       => 'Farmacêutico',
        'image'       => 12,
        'area'        => '800 m²',
        'capacity'    => '264 TR',
        'description' => 'Fluxos laminares e UTAs com expansão indireta para controle de contaminação cruzada.',
    ],
    [
        'slug'        => 'hypera',
        'title'       => 'Hypera Pharma',
        'client'      => 'Hypera',
        'category'    => 'logistico',
        'label'       => 'Logístico',
        'image'       => 16,
        'area'        => '4.000 m²',
        'capacity'    => '200 TR',
        'description' => 'CD Autoportante com climatização VRF e automação integrada Siemens.',
    ],
    [
        'slug'        => 'hypermarcas',
        'title'       => 'Hypermarcas',
        'client'      => 'Hypermarcas',
        'category'    => 'logistico',
        'label'       => 'Logístico',
        'image'       => 15,
        'area'        => '20.000 m²',
        'capacity'    => '500 TR',
        'description' => 'CD Ar-Condicionado com expansão direta (Splitão) e automação Schneider.',
    ],
    [
        'slug'        => 'lakeview',
        'title'       => 'Lake View Resort',
        'client'      => 'Direcional Engenharia',
        'category'    => 'hoteleiro',
        'label'       => 'Hoteleiro',
        'image'       => 3,
        'area'        => '19.968 m²',
        'capacity'    => '502 TR',
        'description' => 'Apart Hotel com 246 apartamentos em Brasília. Sistema Split para apartamentos e áreas comuns.',
    ],
    [
        'slug'        => 'goinn',
        'title'       => 'Estação Goiânia',
        'client'      => 'Hotel GoInn',
        'category'    => 'hoteleiro',
        'label'       => 'Hoteleiro',
        'image'       => 4,
        'area'        => '15.199 m²',
        'capacity'    => '326 TR',
        'description' => 'Hotel com 172 apartamentos, incluindo pressurização de escadas (108.960 m³/h).',
    ],
    [
        'slug'        => 'lineavitta',
        'title'       => 'Linea Vitta',
        'client'      => 'Linea/JR Empreendimentos',
        'category'    => 'comercial',
        'label'       => 'Comercial',
        'image'       => 5,
        'area'        => '27.500 m²',
        'capacity'    => '941 TR',
        'description' => 'Edifício comercial em Brasília com sistema VRF/Split e pressurização de escadas.',
    ],
    [
        'slug'        => 'lineag',
        'title'       => 'Linea G',
        'client'      => 'Linea/JR Empreendimentos',
        'category'    => 'comercial',
        'label'       => 'Comercial',
        'image'       => 9,
        'area'        => '14.600 m²',
        'capacity'    => '513 TR',
        'description' => 'Edifício misto Comercial/Apart hotel com 208 apartamentos, lojas e áreas administrativas.',
    ],
    [
        'slug'        => 'esaf',
        'title'       => 'ESAF',
        'client'      => 'Escola de Administração Fazendária',
        'category'    => 'governamental',
        'label'       => 'Governamental',
        'image'       => 6,
        'area'        => '18.500 m²',
        'capacity'    => '1.220 TR',
        'description' => 'Sistema híbrido VRF-Split (350 TR) + Chiller-Fancoil (870 TR) para a Escola de Administração Fazendária.',
    ],
    [
        'slug'        => 'prf',
        'title'       => 'PRF Vitória',
        'client'      => 'Polícia Rodoviária Federal',
        'category'    => 'governamental',
        'label'       => 'Governamental',
        'image'       => 7,
        'area'        => '6.872 m²',
        'capacity'    => '343 TR',
        'description' => 'Sede da PRF em Vitória-ES com sistema VRF-Split para alojamentos, adm. e auditório.',
    ],
    [
        'slug'        => 'ontex',
        'title'       => 'Ontex',
        'client'      => 'Ontex Global',
        'category'    => 'industrial',
        'label'       => 'Industrial',
        'image'       => 10,
        'area'        => '15.600 m²',
        'capacity'    => '1.050 TR',
        'description' => 'Controle de IBUTG com 710.000 m³/h para produção de fraldas, automação Siemens.',
    ],
    [
        'slug'        => 'savoy',
        'title'       => 'Savoy Cosméticos',
        'client'      => 'Savoy',
        'category'    => 'industrial',
        'label'       => 'Industrial',
        'image'       => 13,
        'area'        => '953 m²',
        'capacity'    => '110.000 m³/h',
        'description' => 'Ventilação e exaustão 100% para linha de envase de aerosóis com girotubo.',
    ],
    [
        'slug'        => 'vitamedic',
        'title'       => 'Vitamedic',
        'client'      => 'Vitamedic Indústria Farmacêutica',
        'category'    => 'logistico',
        'label'       => 'Logístico',
        'image'       => 17,
        'area'        => '7.000 m²',
        'capacity'    => '250 TR',
        'description' => 'CD logístico com expansão direta (splitão), dutos em MPU e automação Siemens.',
    ],
    [
        'slug'        => 'louisdreyfus',
        'title'       => 'Louis Dreyfus',
        'client'      => 'LDC',
        'category'    => 'industrial',
        'label'       => 'Industrial',
        'image'       => 14,
        'area'        => '577 m²',
        'capacity'    => '150 TR',
        'description' => 'Climatização com expansão direta e 03 condicionadores Splitão (91.800 m³/h).',
    ],
];

// Categorias únicas para filtros
$categories = [];
foreach ($projects as $p) {
    $categories[$p['category']] = $p['label'];
}
